# Imports

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

# File Preparation

In [20]:
matches_df = pd.read_parquet("./esta/parsed/matches.parquet")
rounds_df = pd.read_parquet("./esta/parsed/rounds.parquet")
player_frames_df = pd.read_parquet("./esta/parsed/player_frames.parquet") 

idx_pf_df = player_frames_df.set_index(["match_id","round_num"])
idx_r_df = rounds_df.set_index(["match_id","round_num"])
idx_r_df["n_ticks"] = idx_r_df["end_tick"]
image_dim = 1024

In [21]:
tick_cols = [col for col in idx_pf_df.columns if "tick" in col]

start_ticks = idx_r_df["start_tick"].reindex(idx_pf_df.index)

idx_pf_df.loc[:,tick_cols] = idx_pf_df.loc[:,tick_cols].sub(start_ticks,axis=0)

In [22]:
with open(".awpy/maps/map-data.json", "r") as f:
    all_map_data = json.load(f)

In [23]:
idx_pf_df

                                                         steam_id     name  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1          76561197979669175   k0nfig
                                     1          76561198110563159   Lucky
                                     1          76561197990682262    Xyp9x
                                     1          76561198028458803   blameF
                                     1          76561198010511021   gla1ve
...                                                           ...      ...
816e1612-9d2e-4893-af23-bda90c479598 17         76561198004854956  dupreeh
                                     17         76561197983956651   Magisk
                                     17         76561198010511021   gla1ve
                                     17         76561197990682262    Xyp9x
                                     17         76561197987713664   device

                                                    team side            x  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1          Astralis    T -1947.010010
                                     1          Astralis    T -1878.000000
                                     1          Astralis    T -1832.000000
                                     1          Astralis    T -1808.000000
                                     1          Astralis    T -1947.010010
...                                                  ...  ...          ...
816e1612-9d2e-4893-af23-bda90c479598 17         Astralis   CT  -676.580872
                                     17         Astralis   CT -1406.793335
                                     17         Astralis   CT    91.052315
                                     17         Astralis   CT   863.364197
                                     17         Astralis   CT  -344.363220

                                                          y           z  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1          -965.109985 -417.204803
                                     1          -980.000000 -417.254364
                                     1         -1160.000000 -415.968750
                                     1         -1089.000000 -416.728699
                                     1         -1102.109985 -416.633057
...                                                     ...         ...
816e1612-9d2e-4893-af23-bda90c479598 17         2405.284912  -98.822281
                                     17         1042.005737   42.234741
                                     17         2234.848389 -128.262268
                                     17         2628.384277   95.275475
                                     17         1545.462646 -126.093430

                                                velocity_x  velocity_y  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1            0.000000    0.000000
                                     1            0.000000    0.000000
                                     1            0.000000    0.000000
                                     1            0.000000    0.000000
                                     1            0.000000    0.000000
...                                                    ...         ...
816e1612-9d2e-4893-af23-bda90c479598 17          73.553467   90.988373
                                     17          73.553467   90.988373
                                     17          73.553467   90.988373
                                     17          72.240829   92.034019
                                     17          72.240829   92.034019

                                                velocity_z  ...  \
match_id                             round_num              ...
bfa9bbbe-bd16-4713-bd99-745378db05cb 1                 0.0  ...
                                     1                 0.0  ...
                                     1                 0.0  ...
                                     1                 0.0  ...
                                     1                 0.0  ...
...                                                    ...  ...
816e1612-9d2e-4893-af23-bda90c479598 17                0.0  ...
                                     17                0.0  ...
                                     17                0.0  ...
                                     17                0.0  ...
                                     17                0.0  ...

                                                equipment_value_round_start  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1                                  200
                                     1                                  200
                                     1                                  200
                                     1                                  200
                                     1                                  200
...                                                                     ...
816e1612-9d2e-4893-af23-bda90c479598 17                                 200
                                     17                                 850
                                     17                                 200
                                     17                                 200
                                     17                                 200

                                                cash  cash_spend_this_round  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1           150                    650
                                     1           150                    650
                                     1             0                    800
                                     1           150                    650
                                     1             0                    800
...                                              ...                    ...
816e1612-9d2e-4893-af23-bda90c479598 17          400                   3850
                                     17            0                   4250
                                     17         1050                   3750
                                     17          150                   3500
                                     17          100                   4100

                                                cash_spend_total has_helmet  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1                       650      False
                                     1                       650      False
                                     1                       800      False
                                     1                       650      False
                                     1                       800      False
...                                                          ...        ...
816e1612-9d2e-4893-af23-bda90c479598 17                    51350      False
                                     17                    51650      False
                                     17                    50950      False
                                     17                    49600      False
                                     17                    51500      False

                                                has_defuse  has_bomb  ping  \
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1               False      True     2
                                     1               False     False     2
                                     1               False     False     1
                                     1               False     False     2
                                     1               False     False     5
...                                                    ...       ...   ...
816e1612-9d2e-4893-af23-bda90c479598 17              False     False    21
                                     17              False     False    22
                                     17              False     False    11
                                     17              False     False    15
                                     17              False     False    40

                                                zoom_level   tick
match_id                             round_num
bfa9bbbe-bd16-4713-bd99-745378db05cb 1                   0   2560
                                     1                   0   2560
                                     1                   0   2560
                                     1                   0   2560
                                     1                   0   2560
...                                                    ...    ...
816e1612-9d2e-4893-af23-bda90c479598 17                  0  15280
                                     17                  0  15280
                                     17                  0  15280
                                     17                  0  15280
                                     17                  0  15280

[2475576 rows x 43 columns]

In [24]:
selected_map = 'de_mirage'
map_data = all_map_data[selected_map]
selected_matches = matches_df[matches_df.map_name == selected_map]
display(selected_matches.head())
selected_match = selected_matches.iloc[0]
selected_round = 5
sel_idx = (selected_match.match_id,selected_round)

,client_name,map_name,tick_rate,playback_ticks,playback_frames_count,parsed_to_frame_idx,match_id,demo_id,competition_name,hltv_url,match_date,match_name
0,GOTV Demo,de_mirage,127,343251,342767,342784,0839a031-0e2c-4c03-b4bc-b5ba05fe669a,01746483-b3bd-4e4b-a2f2-0de97b17600d,PGL Major Antwerp 2022,https://www.hltv.org/matches/2356160/heroic-vs...,1652781600000,heroic-vs-vitality-pgl-major-antwerp-2022
0,GOTV Demo,de_mirage,127,471790,471564,471581,0a075b4d-576e-46f2-b944-fe9542faee54,04f0fb8f-a4d7-497c-857e-316300fadee3,IEM Katowice 2022,https://www.hltv.org/matches/2354381/furia-vs-...,1645124400000,furia-vs-astralis-iem-katowice-2022
0,GOTV Demo,de_mirage,127,426251,425998,426016,a98ffca7-e968-4a54-9e8f-22f101c2502b,022866a3-090e-42eb-ab8e-aa553a575ada,IEM Katowice 2021,https://www.hltv.org/matches/2346573/faze-vs-f...,1613905200000,faze-vs-furia-iem-katowice-2021
0,GOTV Demo,de_mirage,127,441259,440692,440707,a56115fd-a0ba-4eea-a618-91fd6c57177c,015f7c8d-2bc0-4d83-88e7-60648d2b221c,BLAST Premier Fall Showdown 2021,https://www.hltv.org/matches/2351973/heroic-vs...,1634034600000,heroic-vs-poggerz-blast-premier-fall-showdown-...
0,GOTV Demo,de_mirage,127,493224,492014,492029,f218743d-5e8b-436e-91bd-b7b3664c56c3,0418eb19-853e-4b56-955c-d3eedf2b7e12,BLAST Premier Spring Final 2021,https://www.hltv.org/matches/2349173/natus-vin...,1623853200000,natus-vincere-vs-faze-blast-premier-spring-fin...